//
// GoldenTests — unit tests for the strip-and-append pipeline.
//
// Each fixture consists of these checked-in artifacts:
//
//   - Goldens/Fixtures/<name>.proto              source of truth proto
//   - Goldens/Fixtures/<name>.descriptorset      protoc-compiled descriptor
//   - Goldens/Fixtures/<name>.apple.pb.swift     raw Apple-plugin emit
//   - Goldens/Expected/<name>.pb.swift           post-processed output
//
// At test time we don't shell out to anything. We feed the Apple-emit
// fixture into `SwiftProtobufStripper.strip`, generate a JSON Decodable
// suffix with `DecodableEmitter`, and compare the concatenation byte-for-
// byte against the expected output. This isolates the two pieces of
// logic we actually own (strip rule + Decodable emit) from the moving
// parts owned by Apple.
//
// When Apple's emit changes (new field type, new comment placement, etc.)
// the apple.pb.swift fixture is regenerated by the scripts/regen-goldens
// helper; tests then flag whether our post-processing still produces the
// same expected output.
//

import Foundation
import SwiftProtobuf
import SwiftProtobufPluginLibrary
import Testing

@testable import protoc_gen_swift_json

@Suite("Goldens")
struct GoldenTests {
  /// Every fixture under Goldens/Fixtures/<name>.proto. Adding a new
  /// fixture is just `scripts/regen-goldens.sh` + adding the name here.
  static let fixtures = [
    "books", "closed_enums", "enums", "int64s", "library",
    "maps", "nested", "oneofs", "optionals", "repeated", "scalars",
    "storage",
  ]

  @Test("strip + Decodable emit matches expected", arguments: fixtures)
  func goldensMatch(_ fixture: String) throws {
    try assertGoldenMatches(fixture: fixture)
  }

  // MARK: - coding_key_style

  /// The default emit (camelCase) follows the proto3 JSON spec, so a
  /// multi-word proto field `user_id` becomes the CodingKey raw value
  /// `"userId"`. With `coding_key_style=snake_case` the raw value must
  /// instead be the verbatim proto field name `"user_id"`. This guards
  /// the v0.3 snakeCase emit path, which the golden fixtures (regenerated
  /// with the default option) do not otherwise exercise.
  @Test("snakeCase emit uses verbatim proto field names as CodingKey raw values")
  func snakeCaseCodingKeys() throws {
    let descriptor = try loadFileDescriptor(fixture: "int64s")
    let namer = SwiftProtobufNamer(
      currentFile: descriptor,
      protoFileToModuleMappings: ProtoFileToModuleMappings()
    )

    let camel = DecodableEmitter(
      file: descriptor, namer: namer, codingKeyStyle: .camelCase
    ).emit()
    let snake = DecodableEmitter(
      file: descriptor, namer: namer, codingKeyStyle: .snakeCase
    ).emit()

    // camelCase: proto3 JSON spec lowerCamelCase form.
    #expect(camel.contains(#"= "userId""#))
    #expect(camel.contains(#"= "byteSize""#))
    #expect(!camel.contains(#"= "user_id""#))

    // snakeCase: verbatim proto field names.
    #expect(snake.contains(#"= "user_id""#))
    #expect(snake.contains(#"= "byte_size""#))
    #expect(!snake.contains(#"= "userId""#))
  }

  // MARK: - Harness

  private func assertGoldenMatches(fixture: String) throws {
    let appleEmit = try loadAppleEmit(fixture: fixture)
    let descriptor = try loadFileDescriptor(fixture: fixture)

    let stripped = SwiftProtobufStripper.strip(appleEmit)
    // Mirror PluginRunner's assembly: storage rescued from Apple's binary
    // extension is spliced between the stripped body and the Decodable
    // suffix. Without this a storage-using fixture (e.g. `storage`) would
    // diverge from the real output and, worse, the salvager would go
    // entirely untested by the golden layer.
    let salvagedStorage = StorageSalvager.salvage(from: appleEmit)
    let storageSection =
      salvagedStorage.isEmpty
      ? ""
      : "\n// MARK: - Copy-on-write storage (salvaged from Apple's binary extension)\n\n"
        + salvagedStorage.joined(separator: "\n\n")
        + "\n"
    let namer = SwiftProtobufNamer(
      currentFile: descriptor,
      protoFileToModuleMappings: ProtoFileToModuleMappings()
    )
    let suffix = DecodableEmitter(file: descriptor, namer: namer).emit()
    let actual = stripped + storageSection + "\n" + suffix

    let expected = try loadExpected(named: "\(fixture).pb.swift")
    if actual != expected {
      Issue.record(
        """
        Golden mismatch for \(fixture).proto.

        --- expected ---
        \(expected)
        --- actual ---
        \(actual)
        """
      )
    }
  }

  private func loadAppleEmit(fixture: String) throws -> String {
    let url = goldensRoot
      .appendingPathComponent("Fixtures")
      .appendingPathComponent("\(fixture).apple.pb.swift")
    return try String(contentsOf: url, encoding: .utf8)
  }

  private func loadFileDescriptor(fixture: String) throws -> FileDescriptor {
    let url = goldensRoot
      .appendingPathComponent("Fixtures")
      .appendingPathComponent("\(fixture).descriptorset")
    let data = try Data(contentsOf: url)
    let proto = try Google_Protobuf_FileDescriptorSet(serializedBytes: data)
    let descriptors = DescriptorSet(proto: proto)
    guard let target = descriptors.files.first(where: { $0.name.hasSuffix("\(fixture).proto") })
    else {
      throw GoldenError.fixtureNotInDescriptorSet(fixture)
    }
    return target
  }

  private func loadExpected(named name: String) throws -> String {
    let url = goldensRoot
      .appendingPathComponent("Expected")
      .appendingPathComponent(name)
    return try String(contentsOf: url, encoding: .utf8)
  }

  private var goldensRoot: URL {
    Bundle.module.resourceURL!.appendingPathComponent("Goldens")
  }
}

private enum GoldenError: Error, CustomStringConvertible {
  case fixtureNotInDescriptorSet(String)

  var description: String {
    switch self {
    case .fixtureNotInDescriptorSet(let name):
      return "fixture \(name).proto was not present in the descriptor set"
    }
  }
}
