// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: int64s.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

/// 64-bit integer fixture for swift-protobuf-json's golden harness.
///
/// proto3 JSON spec serialises the int64 family (int64/uint64/sint64/
/// fixed64/sfixed64) as JSON *strings* to dodge JavaScript's 2^53 safe-int
/// limit. This fixture exercises the emitter's number-or-string fallback
/// path (DecodableEmitter.isInt64ish). Field names are intentionally
/// multi-word so the snakeCase CodingKey variant is observable.

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate nonisolated struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

nonisolated struct Goldens_Int64s: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var userID: Int64 = 0

  var byteSize: UInt64 = 0

  var deltaValue: Int64 = 0

  var contentHash: UInt64 = 0

  var fileOffset: Int64 = 0

  var childIds: [Int64] = []

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate nonisolated let _protobuf_package = "goldens"

nonisolated extension Goldens_Int64s: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".Int64s"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}user_id\0\u{3}byte_size\0\u{3}delta_value\0\u{3}content_hash\0\u{3}file_offset\0\u{3}child_ids\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularInt64Field(value: &self.userID) }()
      case 2: try { try decoder.decodeSingularUInt64Field(value: &self.byteSize) }()
      case 3: try { try decoder.decodeSingularSInt64Field(value: &self.deltaValue) }()
      case 4: try { try decoder.decodeSingularFixed64Field(value: &self.contentHash) }()
      case 5: try { try decoder.decodeSingularSFixed64Field(value: &self.fileOffset) }()
      case 6: try { try decoder.decodeRepeatedInt64Field(value: &self.childIds) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.userID != 0 {
      try visitor.visitSingularInt64Field(value: self.userID, fieldNumber: 1)
    }
    if self.byteSize != 0 {
      try visitor.visitSingularUInt64Field(value: self.byteSize, fieldNumber: 2)
    }
    if self.deltaValue != 0 {
      try visitor.visitSingularSInt64Field(value: self.deltaValue, fieldNumber: 3)
    }
    if self.contentHash != 0 {
      try visitor.visitSingularFixed64Field(value: self.contentHash, fieldNumber: 4)
    }
    if self.fileOffset != 0 {
      try visitor.visitSingularSFixed64Field(value: self.fileOffset, fieldNumber: 5)
    }
    if !self.childIds.isEmpty {
      try visitor.visitPackedInt64Field(value: self.childIds, fieldNumber: 6)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Goldens_Int64s, rhs: Goldens_Int64s) -> Bool {
    if lhs.userID != rhs.userID {return false}
    if lhs.byteSize != rhs.byteSize {return false}
    if lhs.deltaValue != rhs.deltaValue {return false}
    if lhs.contentHash != rhs.contentHash {return false}
    if lhs.fileOffset != rhs.fileOffset {return false}
    if lhs.childIds != rhs.childIds {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
