// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: optionals.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

/// proto3 explicit-presence coverage. Each `optional` scalar/enum is
/// backed by Apple with a `_<name>: T?` storage plus `hasXxx` / `clearXxx`
/// accessors. The Decodable emitter must preserve that presence: a missing
/// key has to leave `hasXxx == false`, not eagerly materialize the proto3
/// zero. `plain` is a singular proto3 scalar (no presence) kept as a
/// contrast — it should still collapse to the proto3 default when absent.

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate nonisolated struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

nonisolated enum Goldens_Shade: SwiftProtobuf.Enum, Swift.CaseIterable {
  typealias RawValue = Int
  case unspecified // = 0
  case light // = 1
  case dark // = 2
  case UNRECOGNIZED(Int)

  init() {
    self = .unspecified
  }

  init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .unspecified
    case 1: self = .light
    case 2: self = .dark
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  var rawValue: Int {
    switch self {
    case .unspecified: return 0
    case .light: return 1
    case .dark: return 2
    case .UNRECOGNIZED(let i): return i
    }
  }

  // The compiler won't synthesize support with the UNRECOGNIZED case.
  static let allCases: [Goldens_Shade] = [
    .unspecified,
    .light,
    .dark,
  ]

}

nonisolated struct Goldens_Settings: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var nickname: String {
    get {_nickname ?? String()}
    set {_nickname = newValue}
  }
  /// Returns true if `nickname` has been explicitly set.
  var hasNickname: Bool {self._nickname != nil}
  /// Clears the value of `nickname`. Subsequent reads from it will return its default value.
  mutating func clearNickname() {self._nickname = nil}

  var retries: Int32 {
    get {_retries ?? 0}
    set {_retries = newValue}
  }
  /// Returns true if `retries` has been explicitly set.
  var hasRetries: Bool {self._retries != nil}
  /// Clears the value of `retries`. Subsequent reads from it will return its default value.
  mutating func clearRetries() {self._retries = nil}

  var byteBudget: Int64 {
    get {_byteBudget ?? 0}
    set {_byteBudget = newValue}
  }
  /// Returns true if `byteBudget` has been explicitly set.
  var hasByteBudget: Bool {self._byteBudget != nil}
  /// Clears the value of `byteBudget`. Subsequent reads from it will return its default value.
  mutating func clearByteBudget() {self._byteBudget = nil}

  var muted: Bool {
    get {_muted ?? false}
    set {_muted = newValue}
  }
  /// Returns true if `muted` has been explicitly set.
  var hasMuted: Bool {self._muted != nil}
  /// Clears the value of `muted`. Subsequent reads from it will return its default value.
  mutating func clearMuted() {self._muted = nil}

  var shade: Goldens_Shade {
    get {_shade ?? .unspecified}
    set {_shade = newValue}
  }
  /// Returns true if `shade` has been explicitly set.
  var hasShade: Bool {self._shade != nil}
  /// Clears the value of `shade`. Subsequent reads from it will return its default value.
  mutating func clearShade() {self._shade = nil}

  var plain: String = String()

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _nickname: String? = nil
  fileprivate var _retries: Int32? = nil
  fileprivate var _byteBudget: Int64? = nil
  fileprivate var _muted: Bool? = nil
  fileprivate var _shade: Goldens_Shade? = nil
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate nonisolated let _protobuf_package = "goldens"

nonisolated extension Goldens_Shade: SwiftProtobuf._ProtoNameProviding {
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0SHADE_UNSPECIFIED\0\u{1}SHADE_LIGHT\0\u{1}SHADE_DARK\0")
}

nonisolated extension Goldens_Settings: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".Settings"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}nickname\0\u{1}retries\0\u{3}byte_budget\0\u{1}muted\0\u{1}shade\0\u{1}plain\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self._nickname) }()
      case 2: try { try decoder.decodeSingularInt32Field(value: &self._retries) }()
      case 3: try { try decoder.decodeSingularInt64Field(value: &self._byteBudget) }()
      case 4: try { try decoder.decodeSingularBoolField(value: &self._muted) }()
      case 5: try { try decoder.decodeSingularEnumField(value: &self._shade) }()
      case 6: try { try decoder.decodeSingularStringField(value: &self.plain) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._nickname {
      try visitor.visitSingularStringField(value: v, fieldNumber: 1)
    } }()
    try { if let v = self._retries {
      try visitor.visitSingularInt32Field(value: v, fieldNumber: 2)
    } }()
    try { if let v = self._byteBudget {
      try visitor.visitSingularInt64Field(value: v, fieldNumber: 3)
    } }()
    try { if let v = self._muted {
      try visitor.visitSingularBoolField(value: v, fieldNumber: 4)
    } }()
    try { if let v = self._shade {
      try visitor.visitSingularEnumField(value: v, fieldNumber: 5)
    } }()
    if !self.plain.isEmpty {
      try visitor.visitSingularStringField(value: self.plain, fieldNumber: 6)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Goldens_Settings, rhs: Goldens_Settings) -> Bool {
    if lhs._nickname != rhs._nickname {return false}
    if lhs._retries != rhs._retries {return false}
    if lhs._byteBudget != rhs._byteBudget {return false}
    if lhs._muted != rhs._muted {return false}
    if lhs._shade != rhs._shade {return false}
    if lhs.plain != rhs.plain {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
