//
// CrossPackageStubEmitter.swift
//
// When a field references a top-level type whose containing proto isn't
// part of the current generation scope, the emitted code references a
// Swift type that no .pb.swift in our output defines. The natural fix
// is to add the missing proto to `fileToGenerate`, but in many setups
// the user has deliberately excluded that scope (a different module
// owns it, the dependency is too heavy, etc.).
//
// We take the same stance: synthesise a minimal Decodable stub for
// every out-of-scope top-level type Reachability identified. Decoding
// always yields the zero value:
//
//   - message stub:  empty struct, `init(from:)` returns the empty
//                    instance regardless of input
//   - enum stub:     single `.unknown` case, decoding routes there
//
// Real cross-module data is therefore silently lost on the way out
// (and unrepresentable on the way in). The consumer module compiles,
// but the missing data remains *known* to be missing.
//
// Selected well-known types can opt into a real decoder via plugin
// options (currently: `timestamp_decoder=<TypeName>`). The plugin
// substitutes the delegate type name verbatim — it doesn't import the
// delegate or rely on any specific protocol. The delegate just needs
// to expose a `static func decode(_: String) throws -> Date` matching
// the signature the generated code calls.
//

import Foundation

enum CrossPackageStubEmitter {

  struct Options {
    /// Swift type name that decodes a JSON string into `Foundation.Date`
    /// for `SwiftProtobuf.Google_Protobuf_Timestamp`. `nil` keeps the
    /// default zero-stub behaviour.
    let timestampDecoder: String?
    /// Modules to import in addition to `Foundation` and `SwiftProtobuf`.
    /// Required when a delegate type referenced by another option lives
    /// in a separate module.
    let additionalImports: [String]
    /// When true, emit a real recursive JSON `Decodable` for
    /// `Google_Protobuf_Struct` (+ `Value` / `ListValue`) instead of the
    /// zero-value stub. `false` keeps the default zero-stub behaviour.
    var structDecoder: Bool = false

    static let `default` = Options(timestampDecoder: nil, additionalImports: [])
  }

  /// Returns the contents of a single Swift source file containing one
  /// stub per out-of-scope type. Empty when there's nothing to stub.
  static func emit(
    types: Set<Reachability.OutOfScopeType>,
    options: Options = .default
  ) -> String? {
    guard !types.isEmpty else { return nil }

    var lines: [String] = [
      "//",
      "// Cross-package stubs — generated by protoc-gen-swift-json.",
      "//",
      "// These types live outside the current generation scope. They exist",
      "// only so the in-scope `.pb.swift` files compile; decoding always",
      "// produces the zero value. Real values must be carried through a",
      "// proto that's *in* scope, or by adding the owning proto to your",
      "// fileToGenerate set.",
      "//",
      "",
      "import Foundation",
      "import SwiftProtobuf",
    ]
    for module in options.additionalImports {
      lines.append("import \(module)")
    }
    lines.append("")

    for stub in types.sorted(by: { $0.swiftFullName < $1.swiftFullName }) {
      if stub.isImported {
        if let block = WellKnownDecoders.block(for: stub.swiftFullName, options: options) {
          lines.append(block)
        } else {
          // The type already exists in another Swift module (e.g.
          // SwiftProtobuf's well-known types). Add a retroactive
          // Decodable conformance that silently drops the value —
          // that's enough to make `decodeIfPresent` calls compile.
          lines.append(
            """
            extension \(stub.swiftFullName): @retroactive Decodable {
              public init(from decoder: any Swift.Decoder) throws { self.init() }
            }
            """
          )
        }
      } else if stub.isEnum {
        // Apple's emit names the zero-numbered enum case `unspecified`
        // by convention (stripping the `<EnumName>_UNSPECIFIED` prefix
        // and lowerCamelCasing it). Other in-scope code references the
        // stub as `<StubType>.unspecified`, so the case name has to be
        // exactly that — anything else and the references won't compile.
        lines.append(
          """
          public enum \(stub.swiftFullName): Sendable, Decodable, Equatable {
            case unspecified
            public init(from decoder: any Swift.Decoder) throws { self = .unspecified }
          }
          """
        )
      } else {
        lines.append(
          """
          public struct \(stub.swiftFullName): Sendable, Decodable, Equatable {
            public init() {}
            public init(from decoder: any Swift.Decoder) throws {}
          }
          """
        )
      }
      lines.append("")
    }

    return lines.joined(separator: "\n")
  }
}

/// Real `Decodable` blocks for well-known types when the user opts in
/// via plugin options. The plugin only substitutes the delegate type
/// name — it has no compile-time dependency on the delegate.
private enum WellKnownDecoders {

  static func block(
    for swiftFullName: String,
    options: CrossPackageStubEmitter.Options
  ) -> String? {
    switch swiftFullName {
    case "SwiftProtobuf.Google_Protobuf_Timestamp":
      guard let delegate = options.timestampDecoder else { return nil }
      return timestampBlock(delegate: delegate)
    case "SwiftProtobuf.Google_Protobuf_Struct":
      guard options.structDecoder else { return nil }
      return structBlock()
    default:
      return nil
    }
  }

  /// Recursive JSON `Decodable` for `google.protobuf.Struct` and the
  /// `Value` / `ListValue` it nests, parsing an arbitrary JSON object into
  /// `Struct.fields` so a `google.protobuf.Struct` field carries its
  /// payload instead of decoding to the empty zero-value.
  ///
  /// `Value` / `ListValue` are not themselves in the cross-package stub set
  /// (only `Struct` is referenced by in-scope fields), so emitting their
  /// retroactive conformance here is safe — they'd only collide if a proto
  /// referenced them directly, which `Struct` fields never do.
  private static func structBlock() -> String {
    """
    /// Dynamic key for decoding arbitrary `google.protobuf.Struct` object keys.
    private struct _JSONObjectKey: Swift.CodingKey {
      let stringValue: String
      let intValue: Int? = nil
      init?(stringValue: String) { self.stringValue = stringValue }
      init?(intValue: Int) { return nil }
    }

    extension SwiftProtobuf.Google_Protobuf_Value: @retroactive Decodable {
      public init(from decoder: any Swift.Decoder) throws {
        self.init()
        let container = try decoder.singleValueContainer()
        if container.decodeNil() {
          self.nullValue = .nullValue
        } else if let bool = try? container.decode(Bool.self) {
          self.boolValue = bool
        } else if let number = try? container.decode(Double.self) {
          self.numberValue = number
        } else if let string = try? container.decode(String.self) {
          self.stringValue = string
        } else if let list = try? container.decode(SwiftProtobuf.Google_Protobuf_ListValue.self) {
          self.listValue = list
        } else if let structValue = try? container.decode(SwiftProtobuf.Google_Protobuf_Struct.self) {
          self.structValue = structValue
        }
      }
    }

    extension SwiftProtobuf.Google_Protobuf_ListValue: @retroactive Decodable {
      public init(from decoder: any Swift.Decoder) throws {
        self.init()
        var container = try decoder.unkeyedContainer()
        var values: [SwiftProtobuf.Google_Protobuf_Value] = []
        while !container.isAtEnd {
          values.append(try container.decode(SwiftProtobuf.Google_Protobuf_Value.self))
        }
        self.values = values
      }
    }

    extension SwiftProtobuf.Google_Protobuf_Struct: @retroactive Decodable {
      public init(from decoder: any Swift.Decoder) throws {
        self.init()
        let container = try decoder.container(keyedBy: _JSONObjectKey.self)
        var fields: [String: SwiftProtobuf.Google_Protobuf_Value] = [:]
        for key in container.allKeys {
          fields[key.stringValue] = try container.decode(
            SwiftProtobuf.Google_Protobuf_Value.self, forKey: key
          )
        }
        self.fields = fields
      }
    }
    """
  }

  /// Splits a `Date` into proto's `seconds` (Int64) / `nanos` (Int32)
  /// via the conventional `timeIntervalSince1970` decomposition: floor
  /// the whole-second part, multiply the fractional remainder by 1e9.
  private static func timestampBlock(delegate: String) -> String {
    """
    extension SwiftProtobuf.Google_Protobuf_Timestamp: @retroactive Decodable {
      public init(from decoder: any Swift.Decoder) throws {
        let container = try decoder.singleValueContainer()
        let raw = try container.decode(String.self)
        let date = try \(delegate).decode(raw)
        let interval = date.timeIntervalSince1970
        let wholeSeconds = interval.rounded(.down)
        let seconds = Int64(wholeSeconds)
        let nanos = Int32(((interval - wholeSeconds) * 1_000_000_000).rounded())
        self.init()
        self.seconds = seconds
        self.nanos = nanos
      }
    }
    """
  }
}
