// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: books.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

/// Imports a message defined in library.proto and uses it as a field
/// type. Confirms our DecodableEmitter walks descriptor.dependencies
/// correctly and the resulting Decodable extension references the
/// fully-qualified Swift name produced by Apple.

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate nonisolated struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

nonisolated struct Goldens_Book: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var title: String = String()

  var author: Goldens_Author {
    get {_author ?? Goldens_Author()}
    set {_author = newValue}
  }
  /// Returns true if `author` has been explicitly set.
  var hasAuthor: Bool {self._author != nil}
  /// Clears the value of `author`. Subsequent reads from it will return its default value.
  mutating func clearAuthor() {self._author = nil}

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _author: Goldens_Author? = nil
}

// MARK: - JSON Decodable

extension Goldens_Book: Decodable {
  public enum CodingKeys: String, CodingKey {
    case title = "title"
    case author = "author"
  }

  public init(from decoder: any Swift.Decoder) throws {
    self.init()
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.title = (try? container.decodeIfPresent(String.self, forKey: .title)) ?? ""
    if let v = try? container.decodeIfPresent(Goldens_Author.self, forKey: .author) {
      self.author = v
    }
  }
}
extension Goldens_Book: Equatable {}
