// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: enums.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

/// Enum coverage:
/// - top-level proto3 (open) enum with a zero value
/// - enum used as a message field
/// - enum used in a repeated field

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate nonisolated struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

nonisolated enum Goldens_Status: SwiftProtobuf.Enum, Swift.CaseIterable {
  typealias RawValue = Int
  case unspecified // = 0
  case active // = 1
  case inactive // = 2
  case UNRECOGNIZED(Int)

  init() {
    self = .unspecified
  }

  init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .unspecified
    case 1: self = .active
    case 2: self = .inactive
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  var rawValue: Int {
    switch self {
    case .unspecified: return 0
    case .active: return 1
    case .inactive: return 2
    case .UNRECOGNIZED(let i): return i
    }
  }

  // The compiler won't synthesize support with the UNRECOGNIZED case.
  static let allCases: [Goldens_Status] = [
    .unspecified,
    .active,
    .inactive,
  ]

}

nonisolated struct Goldens_Account: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var status: Goldens_Status = .unspecified

  var history: [Goldens_Status] = []

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

// MARK: - JSON Decodable

extension Goldens_Status: Decodable {
  public init(from decoder: any Swift.Decoder) throws {
    let container = try decoder.singleValueContainer()
    let raw: String
    if let stringValue = try? container.decode(String.self) {
      raw = stringValue
    } else if let intValue = try? container.decode(Int.self) {
      raw = String(intValue)
    } else {
      self = .unspecified
      return
    }
    switch raw {
    case "STATUS_UNSPECIFIED", "0": self = .unspecified
    case "STATUS_ACTIVE", "1": self = .active
    case "STATUS_INACTIVE", "2": self = .inactive
    default:
      self = .UNRECOGNIZED(Int(raw) ?? 0)
    }
  }
}

extension Goldens_Account: Decodable {
  public enum CodingKeys: String, CodingKey {
    case status = "status"
    case history = "history"
  }

  public init(from decoder: any Swift.Decoder) throws {
    self.init()
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.status = (try? container.decodeIfPresent(Goldens_Status.self, forKey: .status)) ?? Goldens_Status.unspecified
    self.history = (try? container.decodeIfPresent([Goldens_Status].self, forKey: .history)) ?? []
  }
}
extension Goldens_Account: Equatable {}
