// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: int64s.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

/// 64-bit integer fixture for swift-protobuf-json's golden harness.
///
/// proto3 JSON spec serialises the int64 family (int64/uint64/sint64/
/// fixed64/sfixed64) as JSON *strings* to dodge JavaScript's 2^53 safe-int
/// limit. This fixture exercises the emitter's number-or-string fallback
/// path (DecodableEmitter.isInt64ish). Field names are intentionally
/// multi-word so the snakeCase CodingKey variant is observable.

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate nonisolated struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

nonisolated struct Goldens_Int64s: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var userID: Int64 = 0

  var byteSize: UInt64 = 0

  var deltaValue: Int64 = 0

  var contentHash: UInt64 = 0

  var fileOffset: Int64 = 0

  var childIds: [Int64] = []

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

// MARK: - JSON Decodable

extension Goldens_Int64s: Decodable {
  public enum CodingKeys: String, CodingKey {
    case userID = "userId"
    case byteSize = "byteSize"
    case deltaValue = "deltaValue"
    case contentHash = "contentHash"
    case fileOffset = "fileOffset"
    case childIds = "childIds"
  }

  public init(from decoder: any Swift.Decoder) throws {
    self.init()
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.userID =
      (try? container.decodeIfPresent(Int64.self, forKey: .userID))
      ?? (try? container.decodeIfPresent(String.self, forKey: .userID)).flatMap(Int64.init)
      ?? 0
    self.byteSize =
      (try? container.decodeIfPresent(UInt64.self, forKey: .byteSize))
      ?? (try? container.decodeIfPresent(String.self, forKey: .byteSize)).flatMap(UInt64.init)
      ?? 0
    self.deltaValue =
      (try? container.decodeIfPresent(Int64.self, forKey: .deltaValue))
      ?? (try? container.decodeIfPresent(String.self, forKey: .deltaValue)).flatMap(Int64.init)
      ?? 0
    self.contentHash =
      (try? container.decodeIfPresent(UInt64.self, forKey: .contentHash))
      ?? (try? container.decodeIfPresent(String.self, forKey: .contentHash)).flatMap(UInt64.init)
      ?? 0
    self.fileOffset =
      (try? container.decodeIfPresent(Int64.self, forKey: .fileOffset))
      ?? (try? container.decodeIfPresent(String.self, forKey: .fileOffset)).flatMap(Int64.init)
      ?? 0
    self.childIds = (try? container.decodeIfPresent([Int64].self, forKey: .childIds)) ?? []
  }
}
extension Goldens_Int64s: Equatable {}
