// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: maps.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

/// Map coverage:
/// - map<string, int32>
/// - map<int32, string>
/// - map<string, Message>

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate nonisolated struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

nonisolated struct Goldens_Cell: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var value: String = String()

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

nonisolated struct Goldens_Sheet: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var counts: Dictionary<String,Int32> = [:]

  var labels: Dictionary<Int32,String> = [:]

  var grid: Dictionary<String,Goldens_Cell> = [:]

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

// MARK: - JSON Decodable

extension Goldens_Cell: Decodable {
  public enum CodingKeys: String, CodingKey {
    case value = "value"
  }

  public init(from decoder: any Swift.Decoder) throws {
    self.init()
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.value = (try? container.decodeIfPresent(String.self, forKey: .value)) ?? ""
  }
}
extension Goldens_Cell: Equatable {}

extension Goldens_Sheet: Decodable {
  public enum CodingKeys: String, CodingKey {
    case counts = "counts"
    case labels = "labels"
    case grid = "grid"
  }

  public init(from decoder: any Swift.Decoder) throws {
    self.init()
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.counts = (try? container.decodeIfPresent([String: Int32].self, forKey: .counts)) ?? [:]
    self.labels = (try? container.decodeIfPresent([Int32: String].self, forKey: .labels)) ?? [:]
    self.grid = (try? container.decodeIfPresent([String: Goldens_Cell].self, forKey: .grid)) ?? [:]
  }
}
extension Goldens_Sheet: Equatable {}
