// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: optionals.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

/// proto3 explicit-presence coverage. Each `optional` scalar/enum is
/// backed by Apple with a `_<name>: T?` storage plus `hasXxx` / `clearXxx`
/// accessors. The Decodable emitter must preserve that presence: a missing
/// key has to leave `hasXxx == false`, not eagerly materialize the proto3
/// zero. `plain` is a singular proto3 scalar (no presence) kept as a
/// contrast — it should still collapse to the proto3 default when absent.

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate nonisolated struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

nonisolated enum Goldens_Shade: SwiftProtobuf.Enum, Swift.CaseIterable {
  typealias RawValue = Int
  case unspecified // = 0
  case light // = 1
  case dark // = 2
  case UNRECOGNIZED(Int)

  init() {
    self = .unspecified
  }

  init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .unspecified
    case 1: self = .light
    case 2: self = .dark
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  var rawValue: Int {
    switch self {
    case .unspecified: return 0
    case .light: return 1
    case .dark: return 2
    case .UNRECOGNIZED(let i): return i
    }
  }

  // The compiler won't synthesize support with the UNRECOGNIZED case.
  static let allCases: [Goldens_Shade] = [
    .unspecified,
    .light,
    .dark,
  ]

}

nonisolated struct Goldens_Settings: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var nickname: String {
    get {_nickname ?? String()}
    set {_nickname = newValue}
  }
  /// Returns true if `nickname` has been explicitly set.
  var hasNickname: Bool {self._nickname != nil}
  /// Clears the value of `nickname`. Subsequent reads from it will return its default value.
  mutating func clearNickname() {self._nickname = nil}

  var retries: Int32 {
    get {_retries ?? 0}
    set {_retries = newValue}
  }
  /// Returns true if `retries` has been explicitly set.
  var hasRetries: Bool {self._retries != nil}
  /// Clears the value of `retries`. Subsequent reads from it will return its default value.
  mutating func clearRetries() {self._retries = nil}

  var byteBudget: Int64 {
    get {_byteBudget ?? 0}
    set {_byteBudget = newValue}
  }
  /// Returns true if `byteBudget` has been explicitly set.
  var hasByteBudget: Bool {self._byteBudget != nil}
  /// Clears the value of `byteBudget`. Subsequent reads from it will return its default value.
  mutating func clearByteBudget() {self._byteBudget = nil}

  var muted: Bool {
    get {_muted ?? false}
    set {_muted = newValue}
  }
  /// Returns true if `muted` has been explicitly set.
  var hasMuted: Bool {self._muted != nil}
  /// Clears the value of `muted`. Subsequent reads from it will return its default value.
  mutating func clearMuted() {self._muted = nil}

  var shade: Goldens_Shade {
    get {_shade ?? .unspecified}
    set {_shade = newValue}
  }
  /// Returns true if `shade` has been explicitly set.
  var hasShade: Bool {self._shade != nil}
  /// Clears the value of `shade`. Subsequent reads from it will return its default value.
  mutating func clearShade() {self._shade = nil}

  var plain: String = String()

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _nickname: String? = nil
  fileprivate var _retries: Int32? = nil
  fileprivate var _byteBudget: Int64? = nil
  fileprivate var _muted: Bool? = nil
  fileprivate var _shade: Goldens_Shade? = nil
}

// MARK: - JSON Decodable

extension Goldens_Shade: Decodable {
  public init(from decoder: any Swift.Decoder) throws {
    let container = try decoder.singleValueContainer()
    let raw: String
    if let stringValue = try? container.decode(String.self) {
      raw = stringValue
    } else if let intValue = try? container.decode(Int.self) {
      raw = String(intValue)
    } else {
      self = .unspecified
      return
    }
    switch raw {
    case "SHADE_UNSPECIFIED", "0": self = .unspecified
    case "SHADE_LIGHT", "1": self = .light
    case "SHADE_DARK", "2": self = .dark
    default:
      self = .UNRECOGNIZED(Int(raw) ?? 0)
    }
  }
}

extension Goldens_Settings: Decodable {
  public enum CodingKeys: String, CodingKey {
    case nickname = "nickname"
    case retries = "retries"
    case byteBudget = "byteBudget"
    case muted = "muted"
    case shade = "shade"
    case plain = "plain"
  }

  public init(from decoder: any Swift.Decoder) throws {
    self.init()
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let v = try? container.decodeIfPresent(String.self, forKey: .nickname) {
      self.nickname = v
    }
    if let v = try? container.decodeIfPresent(Int32.self, forKey: .retries) {
      self.retries = v
    }
    if let v =
      (try? container.decodeIfPresent(Int64.self, forKey: .byteBudget))
      ?? (try? container.decodeIfPresent(String.self, forKey: .byteBudget)).flatMap(Int64.init) {
      self.byteBudget = v
    }
    if let v = try? container.decodeIfPresent(Bool.self, forKey: .muted) {
      self.muted = v
    }
    if let v = try? container.decodeIfPresent(Goldens_Shade.self, forKey: .shade) {
      self.shade = v
    }
    self.plain = (try? container.decodeIfPresent(String.self, forKey: .plain)) ?? ""
  }
}
extension Goldens_Settings: Equatable {}
