// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: scalars.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

/// Phase-1 scalar fixture for swift-protobuf-json's golden test harness.
/// Kept intentionally small (string + int32) so the trimmed MessageEmitter's
/// output stays easy to read at a glance. Wider scalar coverage lands together
/// with Phase-2 emitters.

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate nonisolated struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

nonisolated struct Goldens_Scalars: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var name: String = String()

  var count: Int32 = 0

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

// MARK: - JSON Decodable

extension Goldens_Scalars: Decodable {
  public enum CodingKeys: String, CodingKey {
    case name = "name"
    case count = "count"
  }

  public init(from decoder: any Swift.Decoder) throws {
    self.init()
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.name = (try? container.decodeIfPresent(String.self, forKey: .name)) ?? ""
    self.count = (try? container.decodeIfPresent(Int32.self, forKey: .count)) ?? 0
  }
}
extension Goldens_Scalars: Equatable {}
