// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: closed_enums.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

/// proto2 closed-enum coverage: Apple emits a closed Int-raw-value enum
/// with no UNRECOGNIZED case, so DecodableEmitter must take a different
/// fallback path for unknown wire values.

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate nonisolated struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

nonisolated enum Goldens_Color: Int, SwiftProtobuf.Enum, Swift.CaseIterable {
  case red = 0
  case green = 1
  case blue = 2

  init() {
    self = .red
  }

}

nonisolated struct Goldens_Pixel: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var color: Goldens_Color {
    get {_color ?? .red}
    set {_color = newValue}
  }
  /// Returns true if `color` has been explicitly set.
  var hasColor: Bool {self._color != nil}
  /// Clears the value of `color`. Subsequent reads from it will return its default value.
  mutating func clearColor() {self._color = nil}

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _color: Goldens_Color? = nil
}

// MARK: - JSON Decodable

extension Goldens_Color: Decodable {
  public init(from decoder: any Swift.Decoder) throws {
    let container = try decoder.singleValueContainer()
    let raw: String
    if let stringValue = try? container.decode(String.self) {
      raw = stringValue
    } else if let intValue = try? container.decode(Int.self) {
      raw = String(intValue)
    } else {
      self = .red
      return
    }
    switch raw {
    case "RED", "0": self = .red
    case "GREEN", "1": self = .green
    case "BLUE", "2": self = .blue
    default:
      self = .red
    }
  }
}

extension Goldens_Pixel: Decodable {
  public enum CodingKeys: String, CodingKey {
    case color = "color"
  }

  public init(from decoder: any Swift.Decoder) throws {
    self.init()
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let v = try? container.decodeIfPresent(Goldens_Color.self, forKey: .color) {
      self.color = v
    }
  }
}
extension Goldens_Pixel: Equatable {}
