// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: nested.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

/// Nested type coverage:
/// - nested message inside a message (with its own field referencing
///   itself and the outer message)
/// - nested enum inside a message

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate nonisolated struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

nonisolated struct Goldens_Tree: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var root: Goldens_Tree.Node {
    get {_root ?? Goldens_Tree.Node()}
    set {_root = newValue}
  }
  /// Returns true if `root` has been explicitly set.
  var hasRoot: Bool {self._root != nil}
  /// Clears the value of `root`. Subsequent reads from it will return its default value.
  mutating func clearRoot() {self._root = nil}

  var kind: Goldens_Tree.Kind = .unspecified

  var unknownFields = SwiftProtobuf.UnknownStorage()

  nonisolated enum Kind: SwiftProtobuf.Enum, Swift.CaseIterable {
    typealias RawValue = Int
    case unspecified // = 0
    case binary // = 1
    case nary // = 2
    case UNRECOGNIZED(Int)

    init() {
      self = .unspecified
    }

    init?(rawValue: Int) {
      switch rawValue {
      case 0: self = .unspecified
      case 1: self = .binary
      case 2: self = .nary
      default: self = .UNRECOGNIZED(rawValue)
      }
    }

    var rawValue: Int {
      switch self {
      case .unspecified: return 0
      case .binary: return 1
      case .nary: return 2
      case .UNRECOGNIZED(let i): return i
      }
    }

    // The compiler won't synthesize support with the UNRECOGNIZED case.
    static let allCases: [Goldens_Tree.Kind] = [
      .unspecified,
      .binary,
      .nary,
    ]

  }

  nonisolated struct Node: Sendable {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    var id: String = String()

    var children: [Goldens_Tree.Node] = []

    var unknownFields = SwiftProtobuf.UnknownStorage()

    init() {}
  }

  init() {}

  fileprivate var _root: Goldens_Tree.Node? = nil
}

// MARK: - JSON Decodable

extension Goldens_Tree: Decodable {
  public enum CodingKeys: String, CodingKey {
    case root = "root"
    case kind = "kind"
  }

  public init(from decoder: any Swift.Decoder) throws {
    self.init()
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let v = try? container.decodeIfPresent(Goldens_Tree.Node.self, forKey: .root) {
      self.root = v
    }
    self.kind = (try? container.decodeIfPresent(Goldens_Tree.Kind.self, forKey: .kind)) ?? Goldens_Tree.Kind.unspecified
  }
}
extension Goldens_Tree: Equatable {}

extension Goldens_Tree.Kind: Decodable {
  public init(from decoder: any Swift.Decoder) throws {
    let container = try decoder.singleValueContainer()
    let raw: String
    if let stringValue = try? container.decode(String.self) {
      raw = stringValue
    } else if let intValue = try? container.decode(Int.self) {
      raw = String(intValue)
    } else {
      self = .unspecified
      return
    }
    switch raw {
    case "KIND_UNSPECIFIED", "0": self = .unspecified
    case "KIND_BINARY", "1": self = .binary
    case "KIND_NARY", "2": self = .nary
    default:
      self = .UNRECOGNIZED(Int(raw) ?? 0)
    }
  }
}

extension Goldens_Tree.Node: Decodable {
  public enum CodingKeys: String, CodingKey {
    case id = "id"
    case children = "children"
  }

  public init(from decoder: any Swift.Decoder) throws {
    self.init()
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.id = (try? container.decodeIfPresent(String.self, forKey: .id)) ?? ""
    self.children = (try? container.decodeIfPresent([Goldens_Tree.Node].self, forKey: .children)) ?? []
  }
}
extension Goldens_Tree.Node: Equatable {}
