// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: oneofs.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

/// Oneof coverage:
/// - oneof with scalar members
/// - oneof with a message member

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate nonisolated struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

nonisolated struct Goldens_Image: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var url: String = String()

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

nonisolated struct Goldens_Notification: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var title: String = String()

  var body: Goldens_Notification.OneOf_Body? = nil

  var text: String {
    get {
      if case .text(let v)? = body {return v}
      return String()
    }
    set {body = .text(newValue)}
  }

  var numericCode: Int32 {
    get {
      if case .numericCode(let v)? = body {return v}
      return 0
    }
    set {body = .numericCode(newValue)}
  }

  var image: Goldens_Image {
    get {
      if case .image(let v)? = body {return v}
      return Goldens_Image()
    }
    set {body = .image(newValue)}
  }

  var unknownFields = SwiftProtobuf.UnknownStorage()

  nonisolated enum OneOf_Body: Equatable, Sendable {
    case text(String)
    case numericCode(Int32)
    case image(Goldens_Image)

  }

  init() {}
}

// MARK: - JSON Decodable

extension Goldens_Image: Decodable {
  public enum CodingKeys: String, CodingKey {
    case url = "url"
  }

  public init(from decoder: any Swift.Decoder) throws {
    self.init()
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.url = (try? container.decodeIfPresent(String.self, forKey: .url)) ?? ""
  }
}
extension Goldens_Image: Equatable {}

extension Goldens_Notification: Decodable {
  public enum CodingKeys: String, CodingKey {
    case title = "title"
    case text = "text"
    case numericCode = "numericCode"
    case image = "image"
  }

  public init(from decoder: any Swift.Decoder) throws {
    self.init()
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.title = (try? container.decodeIfPresent(String.self, forKey: .title)) ?? ""
    if let v = try? container.decodeIfPresent(String.self, forKey: .text) {
      self.body = Goldens_Notification.OneOf_Body.text(v)
    } else if let v = try? container.decodeIfPresent(Int32.self, forKey: .numericCode) {
      self.body = Goldens_Notification.OneOf_Body.numericCode(v)
    } else if let v = try? container.decodeIfPresent(Goldens_Image.self, forKey: .image) {
      self.body = Goldens_Notification.OneOf_Body.image(v)
    }
  }
}
extension Goldens_Notification: Equatable {}
