// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: repeated.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

/// Repeated coverage:
/// - repeated scalar
/// - repeated message

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate nonisolated struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

nonisolated struct Goldens_Tag: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var label: String = String()

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

nonisolated struct Goldens_Article: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var keywords: [String] = []

  var tags: [Goldens_Tag] = []

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

// MARK: - JSON Decodable

extension Goldens_Tag: Decodable {
  public enum CodingKeys: String, CodingKey {
    case label = "label"
  }

  public init(from decoder: any Swift.Decoder) throws {
    self.init()
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.label = (try? container.decodeIfPresent(String.self, forKey: .label)) ?? ""
  }
}
extension Goldens_Tag: Equatable {}

extension Goldens_Article: Decodable {
  public enum CodingKeys: String, CodingKey {
    case keywords = "keywords"
    case tags = "tags"
  }

  public init(from decoder: any Swift.Decoder) throws {
    self.init()
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.keywords = (try? container.decodeIfPresent([String].self, forKey: .keywords)) ?? []
    self.tags = (try? container.decodeIfPresent([Goldens_Tag].self, forKey: .tags)) ?? []
  }
}
extension Goldens_Article: Equatable {}
