// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: storage.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

/// Copy-on-write storage coverage.
///
/// Apple's protoc-gen-swift spills a message into a heap `_StorageClass`
/// when it has a singular (non-repeated) message field that recurses back
/// to itself, or when its fields' total cost crosses an internal threshold.
/// A singular self-reference is the smallest, clearest trigger — note this
/// is distinct from `nested.proto`'s Tree.Node, whose self-reference is
/// `repeated` and therefore does NOT spill to storage.
///
/// The struct body Apple keeps above the runtime marker projects every
/// property through `_storage` / `_uniqueStorage()`, whose definitions live
/// in the binary-conformance extension below the marker. StorageSalvager
/// must rescue them or the stripped output references an undefined
/// `_uniqueStorage()` and won't compile. This fixture is the regression
/// guard for that salvage (and for recognising Apple's `nonisolated
/// extension` form).

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate nonisolated struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

nonisolated struct Goldens_LinkedNode: @unchecked Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var value: String {
    get {_storage._value}
    set {_uniqueStorage()._value = newValue}
  }

  var next: Goldens_LinkedNode {
    get {_storage._next ?? Goldens_LinkedNode()}
    set {_uniqueStorage()._next = newValue}
  }
  /// Returns true if `next` has been explicitly set.
  var hasNext: Bool {_storage._next != nil}
  /// Clears the value of `next`. Subsequent reads from it will return its default value.
  mutating func clearNext() {_uniqueStorage()._next = nil}

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _storage = _StorageClass.defaultInstance
}

// MARK: - Copy-on-write storage (salvaged from Apple's binary extension)

extension Goldens_LinkedNode {
  fileprivate class _StorageClass {
    var _value: String = String()
    var _next: Goldens_LinkedNode? = nil
  
      // This property is used as the initial default value for new instances of the type.
      // The type itself is protecting the reference to its storage via CoW semantics.
      // This will force a copy to be made of this reference when the first mutation occurs;
      // hence, it is safe to mark this as `nonisolated(unsafe)`.
      static nonisolated(unsafe) let defaultInstance = _StorageClass()
  
    private init() {}
  
    init(copying source: _StorageClass) {
      _value = source._value
      _next = source._next
    }
  }
  
  fileprivate mutating func _uniqueStorage() -> _StorageClass {
    if !isKnownUniquelyReferenced(&_storage) {
      _storage = _StorageClass(copying: _storage)
    }
    return _storage
  }
  
  static func ==(lhs: Goldens_LinkedNode, rhs: Goldens_LinkedNode) -> Bool {
    if lhs._storage !== rhs._storage {
      let storagesAreEqual: Bool = withExtendedLifetime((lhs._storage, rhs._storage)) { (_args: (_StorageClass, _StorageClass)) in
        let _storage = _args.0
        let rhs_storage = _args.1
        if _storage._value != rhs_storage._value {return false}
        if _storage._next != rhs_storage._next {return false}
        return true
      }
      if !storagesAreEqual {return false}
    }
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

// MARK: - JSON Decodable

extension Goldens_LinkedNode: Decodable {
  public enum CodingKeys: String, CodingKey {
    case value = "value"
    case next = "next"
  }

  public init(from decoder: any Swift.Decoder) throws {
    self.init()
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.value = (try? container.decodeIfPresent(String.self, forKey: .value)) ?? ""
    if let v = try? container.decodeIfPresent(Goldens_LinkedNode.self, forKey: .next) {
      self.next = v
    }
  }
}
extension Goldens_LinkedNode: Equatable {}
